name 'total_dbag'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures total_dbag'
long_description 'Installs/Configures total_dbag'
version '0.2.0'

depends 'apt'
depends 'httpd'